import Navbar from '@/components/Navbar'
import './globals.css'
import { Playfair_Display, Roboto_Mono } from 'next/font/google'

const playfair_display = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair_display',
})

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${playfair_display.variable} ${roboto_mono.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
